"""create vehicle table

Revision ID: 6d30dda6a76f
Revises: 9e55454deeee
Create Date: 2026-03-05 16:57:28.971028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6d30dda6a76f'
down_revision: Union[str, Sequence[str], None] = '9e55454deeee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vendor_id', sa.Uuid(), nullable=False),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('make', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('capacity', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_registration_number'), 'vehicle', ['registration_number'], unique=True)
    op.create_index(op.f('ix_vehicle_vendor_id'), 'vehicle', ['vendor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_vendor_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_registration_number'), table_name='vehicle')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
