"""Initial migration - Create Vendor table

Revision ID: 9e55454deeee
Revises:
Create Date: 2025-08-16 15:42:22.048617

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e55454deeee"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vendor",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("contact_person", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vendor_company_name"), "vendor", ["company_name"], unique=False
    )
    op.create_index(op.f("ix_vendor_email"), "vendor", ["email"], unique=True)
    op.create_index(
        op.f("ix_vendor_phone_number"), "vendor", ["phone_number"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_vendor_phone_number"), table_name="vendor")
    op.drop_index(op.f("ix_vendor_email"), table_name="vendor")
    op.drop_index(op.f("ix_vendor_company_name"), table_name="vendor")
    op.drop_table("vendor")
    # ### end Alembic commands ###
