"""create vehicle table

Revision ID: f8a3167fb4fd
Revises: 9e55454deeee
Create Date: 2026-03-03 01:46:37.005452

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "f8a3167fb4fd"
down_revision: Union[str, Sequence[str], None] = "9e55454deeee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
